dist: bionic
sudo: true
language: python
python:
    - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
before_script:
  - gcc --version
  - python setup.py build_ext --inplace
script:
  # - python -m unittest discover tests -v -v
  - python -m pytest --cov-report=xml --cov=aftercovid tests/
  - python -m flake8 tests
  - python -m flake8 aftercovid
  - python -m flake8 examples
  - python setup.py bdist_wheel
  - python -m aftercovid check
after_script:
  - python -m codecov

  

