environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install -r requirements.txt"
  - "%PYTHON%\\python -m pip install -r requirements-dev.txt"
build: off

before_test:
  - "%PYTHON%\\python -u setup.py build_ext --inplace"

test_script:
  - "%PYTHON%\\python -m unittest discover tests"
  - "%PYTHON%\\python -m flake8 tests"
  - "%PYTHON%\\python -m flake8 aftercovid"
  - "%PYTHON%\\python -m flake8 examples"

after_test:
  - "%PYTHON%\\python setup.py bdist_wheel"
  - "%PYTHON%\\python -m aftercovid check"

artifacts:
  - path: dist
    name: aftercovid
